/**
 * Catalog generator. Reads a Catalog and updates generated surfaces.
 * Block targets patch inline marker blocks. File targets write whole-file output.
 * Throws on missing or malformed markers (never silently skips).
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { Catalog, GenerateTarget, GenerateResult } from "./types.js";

interface GenerateOptions {
  readFile?: (path: string) => string;
  writeFile?: (path: string, content: string) => void;
}

export function generate(
  catalog: Catalog,
  targets: GenerateTarget[],
  opts?: GenerateOptions,
): GenerateResult {
  const readFile = opts?.readFile ?? ((p: string) => readFileSync(p, "utf-8"));
  const writeFile = opts?.writeFile ?? ((p: string, c: string) => writeFileSync(p, c, "utf-8"));

  const patchedFiles: string[] = [];

  for (const target of targets) {
    if ("blockName" in target) {
      const content = readFile(target.filePath);
      const patched = patchBlock(content, target.blockName, target.render(catalog), target.filePath);

      if (patched !== content) {
        writeFile(target.filePath, patched);
        patchedFiles.push(target.filePath);
      }
      continue;
    }

    let content = "";
    try {
      content = readFile(target.filePath);
    } catch (error) {
      const code = (error as NodeJS.ErrnoException | undefined)?.code;
      if (code === "ENOENT") {
        content = "";
      } else {
        throw error;
      }
    }
    const rendered = target.render(catalog);

    if (rendered !== content) {
      mkdirSync(dirname(target.filePath), { recursive: true });
      writeFile(target.filePath, rendered);
      patchedFiles.push(target.filePath);
    }
  }

  return { patchedFiles };
}

function patchBlock(
  content: string,
  blockName: string,
  rendered: string,
  filePath: string,
): string {
  const lines = content.split("\n");
  const beginMarker = `<!-- BEGIN ${blockName} -->`;
  const endMarker = `<!-- END ${blockName} -->`;

  const beginIdx = lines.findIndex((l) => l.trim() === beginMarker);
  if (beginIdx === -1) {
    throw new Error(
      `catalog-compiler: ${filePath} -- missing marker <!-- BEGIN ${blockName} -->`,
    );
  }

  const endIdx = lines.findIndex((l, i) => i > beginIdx && l.trim() === endMarker);
  if (endIdx === -1) {
    throw new Error(
      `catalog-compiler: ${filePath} -- found <!-- BEGIN ${blockName} --> but missing <!-- END ${blockName} -->`,
    );
  }

  const doNotEdit = `<!-- DO NOT EDIT -- generated by catalog-compiler -->`;
  const newBlock = [doNotEdit, rendered].join("\n");
  const newLines = [
    ...lines.slice(0, beginIdx + 1),
    newBlock,
    ...lines.slice(endIdx),
  ];

  return newLines.join("\n");
}
