/**
 * Shared text helpers for generated prompt/install surfaces.
 * Owns marker-block patching and description normalization rules.
 */

export function patchGeneratedBlock(
  content: string,
  blockName: string,
  rendered: string,
  filePath: string,
): string {
  const lines = content.split("\n");
  const beginMarker = `<!-- BEGIN ${blockName} -->`;
  const endMarker = `<!-- END ${blockName} -->`;

  const beginIdx = lines.findIndex((line) => line.trim() === beginMarker);
  if (beginIdx === -1) {
    throw new Error(`catalog-compiler: ${filePath} -- missing marker <!-- BEGIN ${blockName} -->`);
  }

  const endIdx = lines.findIndex((line, index) => index > beginIdx && line.trim() === endMarker);
  if (endIdx === -1) {
    throw new Error(
      `catalog-compiler: ${filePath} -- found <!-- BEGIN ${blockName} --> but missing <!-- END ${blockName} -->`,
    );
  }

  const doNotEdit = "<!-- DO NOT EDIT -- generated by catalog-compiler -->";
  const newBlock = [doNotEdit, rendered].join("\n");
  return [
    ...lines.slice(0, beginIdx + 1),
    newBlock,
    ...lines.slice(endIdx),
  ].join("\n");
}

export function firstSentence(text: string): string {
  const normalized = text.replace(/\s+/g, " ").trim();
  if (!normalized) {
    return "";
  }

  const match = normalized.match(/^.*?[.!?](?=\s|$)/);
  return (match?.[0] ?? normalized).trim();
}
