import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import { describe, expect, it } from "vitest";

import { REPO_ROOT } from "./schema.js";

function read(relativePath: string): string {
  return readFileSync(resolve(REPO_ROOT, relativePath), "utf-8");
}

describe("generated prompt-surface contracts", () => {
  it("keeps the catalog-level Build smoke contract wrapper-based", () => {
    const catalog = read("CIRCUITS.md");

    expect(catalog).toContain("## Smoke Bootstrap Verification");
    expect(catalog).toContain(".circuit/bin/circuit-engine bootstrap");
    expect(catalog).toContain('--manifest "@build"');
    expect(catalog).toContain("Never fabricate those files with `Write`, `Edit`, heredocs, or ad hoc shell writes.");
    expect(catalog).not.toContain(".circuit/plugin-root");
    expect(catalog).not.toContain("CLAUDE_PLUGIN_ROOT");
  });

  it("keeps workflow skill contract blocks generated and local-wrapper based", () => {
    for (const slug of ["build", "explore", "repair", "migrate", "sweep"] as const) {
      const text = read(`skills/${slug}/SKILL.md`);

      expect(text).toContain("<!-- DO NOT EDIT -- generated by catalog-compiler -->");
      expect(text).toContain("## Direct Invocation Contract");
      expect(text).toContain("## Local Helper Wrappers");
      expect(text).toContain(".circuit/bin/");
      expect(text).toContain("Create or validate `.circuit/circuit-runs/<slug>/...` before unrelated repo reads.");
      expect(text).toContain("host-surface verification");
      expect(text).toContain("not valid smoke evidence");
      expect(text).not.toContain(".circuit/plugin-root");
      expect(text).not.toContain("CLAUDE_PLUGIN_ROOT");
    }
  });

  it("keeps run wrapper-based and build-manifest-alias based", () => {
    const runSkill = read("skills/run/SKILL.md");

    expect(runSkill).toContain("<!-- DO NOT EDIT -- generated by catalog-compiler -->");
    expect(runSkill).toContain("/circuit:run develop: ...` resolves to Build");
    expect(runSkill).toContain("Use hook-authored helper wrappers from `.circuit/bin/`.");
    expect(runSkill).toContain(".circuit/bin/circuit-engine bootstrap");
    expect(runSkill).toContain('--manifest "@build"');
    expect(runSkill).toContain("not run-state evidence");
    expect(runSkill).toContain('test -f "$RUN_ROOT/state.json"');
    expect(runSkill).toContain("never use `Write`, `Edit`, heredocs, or manual file creation");
    expect(runSkill).not.toContain(".circuit/plugin-root");
    expect(runSkill).not.toContain("CLAUDE_PLUGIN_ROOT");
  });

  it("keeps utility fast modes generated and wrapper-aware", () => {
    const reviewSkill = read("skills/review/SKILL.md");
    const handoffSkill = read("skills/handoff/SKILL.md");
    const workersSkill = read("skills/workers/SKILL.md");

    expect(reviewSkill).toContain("<!-- DO NOT EDIT -- generated by catalog-compiler -->");
    expect(reviewSkill).toContain("## Fast Modes");
    expect(reviewSkill).toContain(".circuit/bin/compose-prompt");
    expect(reviewSkill).toContain(".circuit/bin/dispatch");

    expect(handoffSkill).toContain("<!-- DO NOT EDIT -- generated by catalog-compiler -->");
    expect(handoffSkill).toContain("/circuit:handoff resume");
    expect(handoffSkill).toContain(".circuit/bin/circuit-engine");
    expect(handoffSkill).toContain(".circuit/bin/gather-git-state");

    expect(workersSkill).toContain("<!-- DO NOT EDIT -- generated by catalog-compiler -->");
    expect(workersSkill).toContain(".circuit/bin/update-batch");
    expect(workersSkill).toContain(".circuit/bin/dispatch");
    expect(workersSkill).not.toContain(".circuit/plugin-root");
  });

  it("ships a generated prompt-contracts manifest for hook consumers", () => {
    const manifest = JSON.parse(read("scripts/runtime/generated/prompt-contracts.json")) as {
      fast_modes: Record<string, { lines: string[] }>;
      helper_wrappers: Array<{ name: string; path: string; target: string }>;
      schema_version: string;
      surfaces: Record<string, { canonical_command?: string; helper_wrappers: string[] }>;
    };

    expect(manifest.schema_version).toBe("1");
    expect(manifest.helper_wrappers).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ name: "circuit-engine", path: ".circuit/bin/circuit-engine" }),
        expect.objectContaining({ name: "compose-prompt", path: ".circuit/bin/compose-prompt" }),
        expect.objectContaining({ name: "dispatch", path: ".circuit/bin/dispatch" }),
      ]),
    );
    expect(manifest.fast_modes.build_smoke.lines.join("\n")).toContain(".circuit/bin/circuit-engine bootstrap");
    expect(manifest.fast_modes.build_smoke.lines.join("\n")).toContain('--manifest "@build"');
    expect(manifest.fast_modes.handoff_resume.lines.join("\n")).toContain("{handoff_path}");
    expect(manifest.surfaces.build.canonical_command).toContain(".circuit/bin/circuit-engine");
    expect(manifest.surfaces.review.helper_wrappers).toContain("compose-prompt");
  });
});

describe("generated command shims", () => {
  it("keeps workflow shims action-first and wrapper-based", () => {
    for (const slug of ["run", "build", "explore", "repair", "migrate", "sweep"] as const) {
      const shim = read(`commands/${slug}.md`);

      expect(shim).toContain("Direct slash-command invocation");
      expect(shim).toContain("Launch the `circuit:");
      expect(shim).toContain("Use hook-authored helper wrappers from `.circuit/bin/`");
      expect(shim).toContain("smoke/bootstrap verification");
      expect(shim).toContain("repo hygiene or branch status alone does not count");
      expect(shim).toContain("compiled contract block");
      expect(shim).not.toContain(".circuit/plugin-root");

      if (slug === "run" || slug === "build") {
        expect(shim).toContain("manual `Write`/`Edit` creation");
        expect(shim).toContain(".circuit/bin/circuit-engine bootstrap");
      }
    }
  });

  it("keeps utility shims fast-mode-first", () => {
    for (const slug of ["review", "handoff"] as const) {
      const shim = read(`commands/${slug}.md`);

      expect(shim).toContain("Direct utility invocation");
      expect(shim).toContain("Launch the `circuit:");
      expect(shim).toContain("Execute argument-selected fast modes before context gathering.");
      expect(shim).toContain("Do not do broad repo exploration unless the utility contract explicitly requires it.");
      expect(shim).toContain(".circuit/bin/");
    }
  });
});
